twig:
    default_path: '%kernel.project_dir%/templates'
    
    # Variables globales Twig
    globals:
        organization_datas: '@App\Twig\OrganizationExtension'
        
      
when@test:
    twig:
        strict_variables: true
